/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_lilifei_learning_jni_JniWrapper */

#ifndef _Included_net_lilifei_learning_jni_JniWrapper
#define _Included_net_lilifei_learning_jni_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_lilifei_learning_jni_JniWrapper
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_lilifei_learning_jni_JniWrapper_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
